services:
  telegram-bot:
    image: ollama-bot
    container_name: tellama
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    volumes:
      - ./ollama-volume:/root/.ollama
    ports:
      - "1337:11434"
